#! /bin/sh

set -e

case "$1" in
    configure)
	    adduser --system \
            --home /var/lib/webdis \
            --no-create-home \
            --gecos "webdis system user" \
            --disabled-password webdis
        chown webdis:adm /var/log/webdis
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


