#! /bin/sh

set -e

case "$1" in
    configure)
	if ! getent passwd webdis>/dev/null; then
	    echo "Creating/updating webdis user account..."
	    adduser --home /var/lib/webdis \
		--gecos "Webdis system user" \
		--system \
		--quiet --disabled-password webdis
	fi
    chown webdis:adm /var/log/webdis
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


