#! /bin/sh

set -e

case "$1" in
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
        ;;

    purge)
        # Since no data is stored in the webdis home directory, the package is
        # not affected by bug #621833 and thus homedir can be safely removed
        deluser --system webdis
        rm -rf /var/log/webdis
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
